In [1]:
import numpy as np

# Initiliazation

In [2]:
#init arrays

one_dim_array = np.array([153,153,153,6,5486,46,46])
two_dim_array = np.array([[153,153,15351,84,86,5],[153153,1,35,15,15,15]])

one_dim_array_modified_type = np.array([153,153,153,6,5486,46,46], dtype = 'int16')
arr = np.array([5.2,1.2,5.1])

In [3]:
#init all zeros 1 dim
a = np.zeros(5)

In [4]:
a.dtype

dtype('float64')

In [73]:
#init all zeros nxm dims, can go further with dims
np.zeros([4,4])
#or
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [81]:
np.zeros(two_dim_array.shape)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [74]:
#init all ones 1 dim
np.ones(5)

array([1., 1., 1., 1., 1.])

In [75]:
#init all ones nxm dims, can go further in dims
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [82]:
np.ones(two_dim_array.shape)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [79]:
#init all n 1dim
np.full((4,),5)

array([5, 5, 5, 5])

In [80]:
#init all n kxm dims
np.full([4,4], 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [84]:
#initializing a sample matrix of another one, by entering ndarray.shape in the shape param
np.full(two_dim_array.shape, 99)

array([[99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99]])

In [87]:
#initializing a sample matrix of another one, by entering the name of the ndarray
np.full_like(two_dim_array, 55)

array([[55, 55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55, 55]])

In [88]:
#init id matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [101]:
#init random decimal matrix, all values are between 0 and 1 by default
np.random.rand(3,3)

array([[0.8798862 , 0.50529304, 0.04527175],
       [0.36602758, 0.05405873, 0.78329093],
       [0.76177458, 0.0303186 , 0.22914493]])

In [107]:
np.random.randint(2,7, size = (3,3))

array([[6, 3, 6],
       [4, 2, 4],
       [3, 3, 2]])

# Exploring

In [19]:
#get dims

two_dim_array.ndim

2

In [20]:
#get shape

two_dim_array.shape


(2, 6)

In [26]:
#get type; here it means the number of bits occupied ny by each element in the array
one_dim_array_modified_type.dtype

dtype('int16')

In [27]:
#get the number of bytes occupied by each element in the array
one_dim_array_modified_type.itemsize

2

In [29]:
#get the number of total bytes occupied by the array
one_dim_array_modified_type.size * one_dim_array_modified_type.itemsize
#or
one_dim_array_modified_type.nbytes

14

In [33]:
#floats occupy by default 8 bytes
arr.dtype

dtype('float64')

In [38]:
#select an element
two_dim_array[1,0]
#or
two_dim_array[1][0]

153153

In [47]:
#get a row [row(s), col(s)]
two_dim_array[0]
#or
two_dim_array[0,:]

array([  153,   153, 15351,    84,    86,     5])

In [48]:
#get a column
two_dim_array[:,0]

array([   153, 153153])

In [49]:
#cotrolling the number of steps [row(s), col(s):stepsize]
two_dim_array[0,::2]

array([  153, 15351,    86])

# Manipulation


In [54]:
#replacing values
two_dim_array[:,2] = [1,5]
two_dim_array

array([[4, 4, 1, 4, 4, 4],
       [4, 4, 5, 4, 4, 4]])

In [55]:
#3d matrix init
tdma = np.array([[[1,2,3],[4,5,6]],
                 [[7,8,9],[10,11,12]]])

In [67]:
#3d matrix value chage
tdma[:,:,0] = [5,56],[8,4]

array([[[ 5,  2,  3],
        [56,  5,  6]],

       [[ 8,  8,  9],
        [ 4, 11, 12]]])

##### N.B. better copy things this way so that vars contains actual copies and not just pointers

In [111]:
a = np.zeros((3,3))
b = a.copy()
b[0,0] = 5
print(a)
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[5. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Mathematics

everything that's doable to values can be done to a np array

In [139]:
a = np.random.rand(3,3)
a

array([[0.58841948, 0.22799566, 0.14708218],
       [0.4578121 , 0.79642136, 0.13941458],
       [0.02196594, 0.33203063, 0.83369743]])

In [126]:
a + 1

array([[1.44817793, 1.44640726, 1.50129743],
       [1.30597538, 1.56756069, 1.00664579],
       [1.58878118, 1.78287718, 1.77574139]])

In [127]:
a - 1

array([[-0.55182207, -0.55359274, -0.49870257],
       [-0.69402462, -0.43243931, -0.99335421],
       [-0.41121882, -0.21712282, -0.22425861]])

In [128]:
a * 5

array([[2.24088963, 2.23203629, 2.50648713],
       [1.52987691, 2.83780344, 0.03322896],
       [2.94390591, 3.91438589, 3.87870693]])

In [129]:
a / 5

array([[0.08963559, 0.08928145, 0.10025949],
       [0.06119508, 0.11351214, 0.00132916],
       [0.11775624, 0.15657544, 0.15514828]])

In [130]:
a // 5 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [131]:
a ** 5

array([[1.80822435e-02, 1.77278568e-02, 3.16575555e-02],
       [2.68183735e-03, 5.88927086e-02, 1.29638388e-11],
       [7.07570319e-02, 2.94081813e-01, 2.80921389e-01]])

In [134]:
a += 1
a

array([[2.44817793, 2.44640726, 2.50129743],
       [2.30597538, 2.56756069, 2.00664579],
       [2.58878118, 2.78287718, 2.77574139]])

In [136]:
a -= 1
a

array([[0.44817793, 0.44640726, 0.50129743],
       [0.30597538, 0.56756069, 0.00664579],
       [0.58878118, 0.78287718, 0.77574139]])

In [137]:
a *= 5
a

array([[2.24088963, 2.23203629, 2.50648713],
       [1.52987691, 2.83780344, 0.03322896],
       [2.94390591, 3.91438589, 3.87870693]])

In [140]:
a /= 5
a

array([[0.1176839 , 0.04559913, 0.02941644],
       [0.09156242, 0.15928427, 0.02788292],
       [0.00439319, 0.06640613, 0.16673949]])

In [141]:
a ** 5

array([[2.25727882e-05, 1.97143681e-07, 2.20267438e-08],
       [6.43555924e-06, 1.02533192e-04, 1.68535327e-08],
       [1.63643661e-12, 1.29134036e-06, 1.28882004e-04]])

In [142]:
a.sum()

0.7089678719020079

In [145]:
np.cos(a)

array([[0.99308324, 0.99896054, 0.99956737],
       [0.99581109, 0.98734106, 0.9996113 ],
       [0.99999035, 0.99779592, 0.98613115]])

In [146]:
np.sin(a)

array([[0.11741244, 0.04558333, 0.02941219],
       [0.09143453, 0.15861158, 0.0278793 ],
       [0.00439317, 0.06635733, 0.16596794]])

In [147]:
b = np.sin(a)

In [148]:
a + b

array([[0.23509634, 0.09118246, 0.05882863],
       [0.18299695, 0.31789585, 0.05576222],
       [0.00878636, 0.13276346, 0.33270743]])

In [151]:
a-a 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [152]:
a - b

array([[2.71455803e-04, 1.58005904e-05, 4.24228791e-06],
       [1.27884666e-04, 6.72692344e-04, 3.61282093e-06],
       [1.41314863e-08, 4.87952364e-05, 7.71543442e-04]])

In [153]:
a * b

array([[1.38175536e-02, 2.07856031e-03, 8.65201938e-04],
       [8.37196717e-03, 2.52643301e-02, 7.77356266e-04],
       [1.93000430e-05, 4.40653326e-03, 2.76734091e-02]])

Linear Algebra

In [156]:
a = np.ones((2,3))
b = np.full((3,2), 2)

In [157]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [158]:
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [161]:
#this is actual matrices multiplication, the one with * does only multiply corresponding values for each matrix
#to be able to this calculation we need m of a to be equal to n of b
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [162]:
#get the determinant of a matrix
c = np.identity(3)
np.linalg.det(c)

1.0

##### stats

In [165]:
mt = np.random.randint(7, size = (3,3))
mt

array([[5, 5, 6],
       [5, 1, 3],
       [0, 4, 5]])

In [ ]:
#if the axis param is specified, then min or max is gonna be for each row(1) or for each col(0)

In [168]:
np.min(mt, axis = 0)

array([0, 1, 3])

In [169]:
np.max(mt, axis = 1)

array([6, 5, 5])

##### reorganizing arrays

In [213]:
a = np.random.randint(10, size = (4,5))
a

array([[3, 3, 0, 4, 8],
       [1, 7, 4, 8, 6],
       [3, 7, 3, 0, 8],
       [1, 6, 0, 7, 3]])

In [214]:
m = a.reshape(5,2,2)

In [205]:
#vertical and horizontal stacking
a = np.random.randint(5,size = (5))
b = np.random.randint(5,size = (5))
k = np.random.randint(5,size = (2,5))

In [191]:
a

array([1, 1, 1, 2, 0])

In [192]:
b

array([0, 4, 0, 4, 0])

In [207]:
#increases diminsionality
c = np.vstack([a,b])
c

array([[4, 0, 0, 4, 2],
       [4, 0, 3, 0, 1]])

In [211]:
np.vstack([k,c])

array([[1, 1, 2, 2, 2],
       [0, 1, 2, 1, 2],
       [4, 0, 0, 4, 2],
       [4, 0, 3, 0, 1]])

In [210]:
np.hstack([k,c])

array([[1, 1, 2, 2, 2, 4, 0, 0, 4, 2],
       [0, 1, 2, 1, 2, 4, 0, 3, 0, 1]])

In [208]:
k

array([[1, 1, 2, 2, 2],
       [0, 1, 2, 1, 2]])

In [197]:
#
np.hstack((a,b))

array([1, 1, 1, 2, 0, 0, 4, 0, 4, 0])

In [215]:
a

array([[3, 3, 0, 4, 8],
       [1, 7, 4, 8, 6],
       [3, 7, 3, 0, 8],
       [1, 6, 0, 7, 3]])

In [216]:
b

array([4, 0, 3, 0, 1])

In [217]:
c

array([[4, 0, 0, 4, 2],
       [4, 0, 3, 0, 1]])

In [218]:
k

array([[1, 1, 2, 2, 2],
       [0, 1, 2, 1, 2]])

In [219]:
m

array([[[3, 3],
        [0, 4]],

       [[8, 1],
        [7, 4]],

       [[8, 6],
        [3, 7]],

       [[3, 0],
        [8, 1]],

       [[6, 0],
        [7, 3]]])

In [229]:
np.vstack((np.zeros(5),np.zeros(5)))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [233]:
np.hstack((c,k))

array([[4, 0, 0, 4, 2, 1, 1, 2, 2, 2],
       [4, 0, 3, 0, 1, 0, 1, 2, 1, 2]])

##### if the involved matrices are exactly the same, then a vstack and an hstack are doable
##### if the involved matrices have an equal number of rows, then only an hstack is doable
##### if the involved matrices have an equal number of cols, then only a vstack is doable

##### Boolean masking and advanced indexing

In [239]:
mt = np.random.randint(1000, size = (10,10))
mt

array([[476,   9, 637, 448, 524, 567, 933, 811, 378, 561],
       [679, 120, 182, 434, 124, 755, 975, 302, 781,  73],
       [996, 350, 944, 685, 550,  19, 750, 703, 447, 906],
       [225, 371, 596, 394, 835, 478, 713, 653, 348, 878],
       [275, 382, 871, 105, 862, 769, 295, 193, 494, 724],
       [729, 964,  92, 349, 335, 983, 860, 929, 118,   8],
       [960, 323, 729, 162, 597, 828, 491, 448, 105, 412],
       [286, 900, 755, 332, 225, 200, 409,   0, 503, 737],
       [605, 516, 703, 915, 252, 776, 409, 503, 687, 725],
       [106, 873, 374, 877, 349, 984, 449,  34, 862, 777]])

In [236]:
mt < 100

array([[False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False,  True, False,  True, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
         True]])

In [237]:
mt[mt < 100]

array([35, 43, 50, 13])

In [244]:
mt[[1,6,8],2]

array([182, 729, 703])

In [247]:
np.all(np.zeros(5) == 0)

True

In [249]:
np.any(mt > 50, axis = 0)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [250]:
np.any(mt < 50, axis = 1)

array([ True, False,  True, False, False,  True, False,  True, False,
        True])

In [253]:
((mt > 50)&(mt < 100))

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False,  True, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [256]:
(~((mt > 50)&(mt < 100))) #~ means NOT

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True, False,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [257]:
a=  np.random.randint(50, size = (6,5))

In [258]:
a

array([[32, 47,  5, 11, 19],
       [ 3, 18, 39,  1, 40],
       [43, 10, 49,  1, 43],
       [ 4, 19,  6, 44, 49],
       [17,  3,  9, 38,  5],
       [16, 35,  2, 15, 22]])

In [268]:
a[2:4,0:2]

array([[43, 10],
       [ 4, 19]])

In [271]:
a[[0,1,2,3], 1:5]

array([[47,  5, 11, 19],
       [18, 39,  1, 40],
       [10, 49,  1, 43],
       [19,  6, 44, 49]])

In [273]:
a[[0,4,5],3:]

array([[11, 19],
       [38,  5],
       [15, 22]])

# Useful Links


NumPy vs Lists:
https://jakevdp.github.io/blog/2014/0...

Indexing: 
https://docs.scipy.org/doc/numpy-1.13...

Array Creation Routines:
https://docs.scipy.org/doc/numpy/refe...

Math Routines Docs:
https://docs.scipy.org/doc/numpy/refe...

Linear Algebra Docs:
https://docs.scipy.org/doc/numpy/refe...